export const menuItems = [
  {
    img: "/burger.png",
    title: "Chicken Cripsy Burger",
    desc: "Try our crispy chicken burger with lettuce, tomato, and our special sauce",
    price: "21.90",
    category: "fastFood",
  },
  {
    img: "/friedchicken.png",
    title: "Spicy Fried Chicken",
    desc: "Experience the best fried chicken in town with our signature spicy sauce",
    price: "20.90",
    category: "fastFood",
  },
  {
    img: "/fries.png",
    title: "Super Duper Fries",
    desc: "Our signature fries with a side of our special sauce",
    price: "20.90",
    category: "fastFood",
  },
  {
    img: "/hotdog.png",
    title: "Hot Dog",
    desc: "Our signature hot dog with a side of our special sauce",
    price: "20.90",
    category: "fastFood",
  },
  {
    img: "/dessert1.png",
    title: "Tira Dont Miss This",
    desc: "Our signature tiramisu with a side of our special sauce",
    price: "24.90",
    category: "dessert",
  },
  {
    img: "/dessert2.png",
    title: "Ice Age Vanilla",
    desc: "Our signature vanilla ice cream with a side of our special sauce",
    price: "16.90",
    category: "dessert",
  },
  {
    img: "/dessert3.png",
    title: "Soft Cookies Mama",
    desc: "Our signature cookies with a side of our special sauce",
    price: "22.90",
    category: "dessert",
  },
  {
    img: "/dessert4.png",
    title: "Soft Cookies Papa",
    desc: "Our signature cookies with a side of our special flavour",
    price: "22.90",
    category: "dessert",
  },
  {
    img: "/macarons.png",
    title: "Helena Macarons",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "dessert",
  },
  {
    img: "/nasi1.png",
    title: "Nasi Ayam",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "anekanasi",
  },
  {
    img: "/nasi2.png",
    title: "Nasi Geprek",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "anekanasi",
  },
  {
    img: "/nasi3.png",
    title: "Ayam Gepuks",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "anekanasi",
  },
  {
    img: "/drink1.png",
    title: "Root Beer",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "10.00",
    category: "drink",
    customizations: [
      {
        title: "Choice of Size",
        type: "radio",
        required: true,
        options: [
          { value: "regular", label: "Regular" },
          { value: "large", label: "Large", extra: "+ RM1.00" },
        ],
      },
      {
        title: "Choice of Cup",
        type: "radio",
        required: true,
        options: [
          { value: "normal", label: "Normal" },
          { value: "specialCup", label: "Special Cup Alabama", extra: "+ RM5.00" },
        ],
      },
    ],
    addons: [
      {
        type: "checkbox",
        required: false,
        options: [
          { value: "noice", addOnPrice: 1.00, label: "Vanilla Ice Cream" },
          { value: "ice", addOnPrice: 0.50, label: "Chocolate Rice" },
        ],
      },
    ],
  },
  {
    img: "/drink2.png",
    title: "Pee Pee Ice",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "drink",
  },
  {
    img: "/drink3.png",
    title: "Strawberry Mama",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "drink",
  },
  {
    img: "/drink3.png",
    title: "Strawberry Mama",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "massage",
  },
];
