export const menuItems = [
  {
    img: "/burger.png",
    title: "Chicken Cripsy Burger",
    desc: "Try our crispy chicken burger with lettuce, tomato, and our special sauce",
    price: "21.90",
    category: "fastFood",
  },
  {
    img: "/friedchicken.png",
    title: "Spicy Fried Chicken",
    desc: "Experience the best fried chicken in town with our signature spicy sauce",
    price: "20.90",
    category: "fastFood",
  },
  {
    img: "/fries.png",
    title: "Super Duper Fries",
    desc: "Our signature fries with a side of our special sauce",
    price: "20.90",
    category: "fastFood",
  },
  {
    img: "/hotdog.png",
    title: "Hot Dog",
    desc: "Our signature hot dog with a side of our special sauce",
    price: "20.90",
    category: "fastFood",
  },
  {
    img: "/dessert1.png",
    title: "Tira Dont Miss This",
    desc: "Our signature tiramisu with a side of our special sauce",
    price: "24.90",
    category: "dessert",
  },
  {
    img: "/dessert2.png",
    title: "Ice Age Vanilla",
    desc: "Our signature vanilla ice cream with a side of our special sauce",
    price: "16.90",
    category: "dessert",
  },
  {
    img: "/dessert3.png",
    title: "Soft Cookies Mama",
    desc: "Our signature cookies with a side of our special sauce",
    price: "22.90",
    category: "dessert",
  },
  {
    img: "/dessert4.png",
    title: "Soft Cookies Papa",
    desc: "Our signature cookies with a side of our special flavour",
    price: "22.90",
    category: "dessert",
  },
  {
    img: "/macarons.png",
    title: "Helena Macarons",
    desc: "From west to east, HelenaMa is a must-try for all macaron lovers",
    price: "22.90",
    category: "dessert",
  },
];
