import type { Metadata } from "next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Theme
          accentColor="jade"
          grayColor="mauve"
          panelBackground="solid"
          scaling="110%"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
